version: '3'

######## admin-api 启动本项目之前，要先启动本项目依赖的环境docker-compose-env.yml #######

services:
  #总后台admin-api , admin只有一个聚合服务，通过rpc调用looklook中的rpc做业务交互，不走nginx-gateway网关了，直接暴露端口给后端的web-vue访问就好了
  admin-api:
    image: cosmtrek/air:v1.28.0
    container_name: admin-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    working_dir: /go/src/github.com/looklook/admin
    ports:
      - 7888:8888
    volumes:
      - .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net


networks:
  looklook_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

